model = "gpt-5.5"
personality = "pragmatic"
model_reasoning_effort = "high"

[projects."/home/vinz"]
trust_level = "trusted"

[projects."/home/vinz/Github/weeecs"]
trust_level = "trusted"
sandbox_mode = "workspace-write"

[projects."/home/vinz/Github/tablioscope"]
trust_level = "trusted"

[projects."/home/vinz/Github/my-catalogue"]
trust_level = "trusted"

[projects."/home/vinz/Downloads/KPop Demon Hunters Cast - KPop Demon Hunters (Soundtrack from the Netflix Film) (2025) [24Bit-48kHz] FLAC [PMEDIA] ⭐️"]
trust_level = "trusted"

[projects."/mnt/usb/TMP"]
trust_level = "trusted"

[projects."/home/vinz/RP3"]
trust_level = "trusted"

[projects."/home/vinz/Github/dotfiles"]
trust_level = "trusted"

[projects."/home/vinz/Github/alacritty"]
trust_level = "trusted"

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
"gpt-5.3-codex" = "gpt-5.4"

[shell_environment_policy]
set = { USER = "codex" }

[tui]
status_line = ["model-with-reasoning", "five-hour-limit"]
theme = "zenburn"

[tui.model_availability_nux]
"gpt-5.5" = 3

[plugins."github@openai-curated"]
enabled = true

[mcp_servers.playwright]
command = "npx"
args = [
  "-y",
  "@playwright/mcp@latest",
  "--browser", "firefox",
  "--user-data-dir", "/home/vinz/.cache/codex-firefox-profile",
  "--viewport-size", "1400x900"
]
